version: "3.9"

services:
    db-postgres-15:
        image: postgres:15
        container_name: local-postgres
        restart: "unless-stopped"
        ports:
            - 5432:5432
        environment:
            - POSTGRES_DB=dev
            - POSTGRES_MULTIPLE_DATABASES=test,stage,prod
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=pw2023
            - POSTGRES_INITDB_ARGS="--encoding=UTF8"
        networks:
            - local-linux
        volumes:
            - postgres_data:/docker-entrypoint-initdb.d
    redis-7:
        image: redis:7
        container_name: local-redis
        restart: "unless-stopped"
        ports:
          - 6379:6379
        networks:
            - local-linux
        volumes:
            - redis_data:/usr/local/etc/redis
        command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
volumes:
    postgres_data:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: ./docker/postgres
    redis_data:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: ./docker/redis
networks:
    local-linux: