"""system email

Revision ID: e52fb6232455
Revises: 76b572b1108a
Create Date: 2024-05-23 19:20:45.624610

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e52fb6232455'
down_revision: Union[str, None] = '76b572b1108a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_email',
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('PRODUCT', 'OTHER', name='notificationtype'), nullable=False),
    sa.Column('is_sent', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('task_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('system_email')
    # ### end Alembic commands ###
